controllers:
    resource: ../src/Controller/
    type: annotation

# This enables the new PSR-4 route loading:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: annotation
